import { adminDb } from "@/lib/firebase-admin";
import { requireSessionAccess } from "@/lib/guided-authorization";
import { parsePersistedAnswer, parsePersistedCandidate, parsePersistedClarification, type DocumentationSession } from "@/lib/guided-documentation";
import { parsePersistedProcedure, parsePersistedProcedureStep, type PersistedProcedure } from "@/lib/procedures";
import { parsePersistedOrganizationUnit } from "@/lib/organization-units";
import { parsePersistedCompanyUser } from "@/lib/tenant-auth";
import type { CompanyUser } from "@/lib/tenant-auth";
import type { CandidateQualityContext, DiscoveryQualityContext, ProcedureQualityContext } from "@/lib/quality-types";
import { discoveryQuestionIds } from "@/lib/quality-engine";

export class QualityDataError extends Error { constructor(message: string, public readonly status: 400 | 404 | 409 = 409) { super(message); } }
function sameSession(value: { companyId: string; projectId: string; organizationUnitId: string; sessionId: string }, session: DocumentationSession) { return value.companyId === session.companyId && value.projectId === session.projectId && value.organizationUnitId === session.organizationUnitId && value.sessionId === session.id; }
async function loadSessionEvidence(session: DocumentationSession) {
  const [answerSnapshot, candidateSnapshot, clarificationSnapshot] = await Promise.all([
    adminDb.collection("guidedAnswers").where("sessionId", "==", session.id).limit(2101).get(), adminDb.collection("procedureCandidates").where("sessionId", "==", session.id).limit(101).get(), adminDb.collection("clarificationItems").where("sessionId", "==", session.id).limit(201).get(),
  ]);
  if (answerSnapshot.size > 2100 || candidateSnapshot.size > 100 || clarificationSnapshot.size > 200) throw new QualityDataError("Assessment source exceeds its supported bound.");
  const answers = answerSnapshot.docs.map((doc) => parsePersistedAnswer(doc.id, doc.data())); const candidates = candidateSnapshot.docs.map((doc) => parsePersistedCandidate(doc.id, doc.data())); const clarifications = clarificationSnapshot.docs.map((doc) => parsePersistedClarification(doc.id, doc.data()));
  if (answers.some((item) => !item || !sameSession(item, session)) || candidates.some((item) => !item || !sameSession(item, session)) || clarifications.some((item) => !item || !sameSession(item, session))) throw new QualityDataError("Assessment source relationship is invalid.");
  return { answers: answers.filter((item) => item !== null), candidates: candidates.filter((item) => item !== null), clarifications: clarifications.filter((item) => item !== null) };
}
export async function loadDiscoveryQualityContext(sessionId: string, actor: CompanyUser): Promise<DiscoveryQualityContext> { const session = await requireSessionAccess(sessionId, actor); const evidence = await loadSessionEvidence(session); return Object.freeze({ session, ...evidence, applicableQuestionIds: discoveryQuestionIds(session.discoveryPromptSetVersion) }); }
export async function loadCandidateQualityContext(sessionId: string, candidateId: string, actor: CompanyUser): Promise<CandidateQualityContext> { const session = await requireSessionAccess(sessionId, actor); const [candidateSnapshot, answerSnapshot, clarificationSnapshot] = await Promise.all([adminDb.collection("procedureCandidates").doc(candidateId).get(), adminDb.collection("guidedAnswers").where("candidateId", "==", candidateId).limit(2101).get(), adminDb.collection("clarificationItems").where("candidateId", "==", candidateId).limit(201).get()]); const candidate = candidateSnapshot.exists ? parsePersistedCandidate(candidateSnapshot.id, candidateSnapshot.data()) : null; if (!candidate || !sameSession(candidate, session)) throw new QualityDataError("Procedure candidate not found.", 404); if (answerSnapshot.size > 2100 || clarificationSnapshot.size > 200) throw new QualityDataError("Assessment source exceeds its supported bound."); const answers = answerSnapshot.docs.map((doc) => parsePersistedAnswer(doc.id, doc.data())); const clarifications = clarificationSnapshot.docs.map((doc) => parsePersistedClarification(doc.id, doc.data())); if (answers.some((item) => !item || !sameSession(item, session) || item.candidateId !== candidate.id) || clarifications.some((item) => !item || !sameSession(item, session) || item.candidateId !== candidate.id)) throw new QualityDataError("Candidate assessment source relationship is invalid."); return Object.freeze({ session, candidate, answers: answers.filter((item) => item !== null), clarifications: clarifications.filter((item) => item !== null) }); }
export async function loadProcedureQualityContext(procedure: PersistedProcedure): Promise<ProcedureQualityContext> { const snapshot = await adminDb.collection("procedureSteps").where("procedureId", "==", procedure.id).limit(101).get(); if (snapshot.size > 100) throw new QualityDataError("Assessment source exceeds its supported bound."); const steps = snapshot.docs.map((doc) => parsePersistedProcedureStep(doc.id, doc.data())); if (steps.some((step) => !step || step.companyId !== procedure.companyId || step.projectId !== procedure.projectId || step.procedureId !== procedure.id)) throw new QualityDataError("Procedure-step relationship is invalid."); const validSteps = steps.filter((step) => step !== null); const unitIds = [...new Set(validSteps.flatMap((step) => step.organizationUnitId ? [step.organizationUnitId] : []))]; const userIds = [...new Set(validSteps.flatMap((step) => [step.performer, step.review?.performer, step.approval?.performer].flatMap((performer) => performer?.type === "user" && performer.userId ? [performer.userId] : [])))]; const refs = [...unitIds.map((id) => adminDb.collection("organizationUnits").doc(id)), ...userIds.map((id) => adminDb.collection("users").doc(id))]; const references = refs.length ? await adminDb.getAll(...refs) : []; for (let index = 0; index < unitIds.length; index++) { const item = references[index]; const unit = item?.exists ? parsePersistedOrganizationUnit(item.id, item.data()) : null; if (!unit || !unit.active || unit.companyId !== procedure.companyId) throw new QualityDataError("Procedure organization-unit reference is invalid."); } for (let index = 0; index < userIds.length; index++) { const item = references[unitIds.length + index]; const user = item?.exists ? parsePersistedCompanyUser(item.id, item.data()) : null; if (!user || !user.active || user.companyId !== procedure.companyId) throw new QualityDataError("Procedure performer reference is invalid."); } return Object.freeze({ procedure, steps: validSteps }); }
export async function loadProcedureForQuality(procedureId: string) { const snapshot = await adminDb.collection("procedures").doc(procedureId).get(); const procedure = snapshot.exists ? parsePersistedProcedure(snapshot.id, snapshot.data()) : null; if (!procedure) throw new QualityDataError("Procedure not found.", 404); return procedure; }
