"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import QualityPanel from "@/components/QualityPanel";

type Context = { user: { id: string; companyId: string; role: string }; projects: Array<{ id: string; name: string }>; organizationUnits: Array<{ id: string; name: string }>; writableOrganizationUnitIds: string[] };
type Subject = { id: string; name: string; email: string };
type Session = { id: string; companyId: string; projectId: string; organizationUnitId: string; subjectType: "user" | "organization_unit"; subjectUserId?: string; phase: string; status: string; active: boolean };
type Candidate = { id: string; label: string; classification: string; status: string; procedureId?: string };
type Question = { id: string; stage: string; promptAr: string; helpAr?: string; answerKind: "text" | "choice" | "boolean" | "number" | "duration" | "reference" | "items"; choices?: string[]; uncertainty: boolean };
type NextState = { stage: string; subjectType?: "session" | "candidate" | "step"; subjectKey?: string; stepKey?: string; stepNumber?: number; recommendation?: string; blockers?: number; warnings?: number; nextQuestion: Question | null };
type Clarification = { id: string; summary: string; severity: "required" | "recommended"; status: string; questionId: string; subjectType: "session" | "candidate" | "step"; subjectKey: string; stepKey?: string };
type Answer = { id: string; questionId: string; subjectKey: string; stepKey?: string; answer: Record<string, unknown> & { kind: string }; certainty: string };

class ApiError extends Error { constructor(message: string, readonly status: number) { super(message); } }
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const body = await response.json() as T & { message?: string }; if (!response.ok) throw new ApiError(body.message ?? "تعذر إكمال الطلب.", response.status); return body; }
const inputClass = "w-full rounded-xl border border-slate-300 bg-white px-3 py-2";
const primary = "rounded-xl bg-blue-700 px-4 py-2 font-semibold text-white disabled:opacity-50";
const certaintyLabels = { confirmed: "متأكد", approximate: "تقريبًا", unknown: "مش عارف", needs_check: "محتاج أتأكد", conditional: "حسب الحالة" } as const;
const summaryLabels: Record<string, string> = { "procedure.name": "اسم الإجراء", "procedure.objective": "الهدف", "procedure.trigger.type": "نوع البداية", "procedure.trigger.description": "وصف البداية", "procedure.frequency.type": "التكرار", "procedure.inputs": "مدخلات الإجراء", "procedure.outputs": "مخرجات الإجراء", "step.name": "العمل", "step.performer.type": "نوع المنفذ", "step.performer.user": "الموظف المنفذ", "step.performer.role": "الدور المنفذ", "step.organization_unit": "الوحدة التنظيمية", "step.inputs": "المدخلات", "step.outputs": "المخرجات", "step.systems": "الأنظمة", "step.documents": "المستندات", "step.required_permissions": "الصلاحيات التشغيلية", "step.timing.processing": "وقت التنفيذ", "step.timing.waiting": "وقت الانتظار", "step.review.required": "المراجعة مطلوبة", "step.review.performer": "مسؤول المراجعة", "step.approval.required": "الاعتماد مطلوب", "step.approval.performer": "صاحب الاعتماد", "step.approval.condition": "شرط الاعتماد", "step.decision.is_decision": "نقطة قرار", "step.decision.question": "سؤال القرار", "step.exceptions": "الاستثناءات", "step.continue": "توجد خطوة تالية", "confirmation.final": "التأكيد النهائي" };
function displayAnswer(answer: Answer["answer"]) { if (Array.isArray(answer.values)) return answer.values.map((item) => typeof item === "object" && item ? Object.values(item).filter((value) => typeof value === "string").join(" — ") : String(item)).join("، ") || "لا يوجد"; if (typeof answer.referenceId === "string") return answer.referenceId; if (typeof answer.value === "number" && typeof answer.unit === "string") return `${answer.value} ${answer.unit}`; if (typeof answer.value === "boolean") return answer.value ? "نعم" : "لا"; return String(answer.value ?? "—"); }

export default function GuidedDocumentationClient() {
  const [context, setContext] = useState<Context | null>(null); const [projectId, setProjectId] = useState(""); const [unitId, setUnitId] = useState("");
  const [subjects, setSubjects] = useState<Subject[]>([]); const [subjectType, setSubjectType] = useState<"user" | "organization_unit">("user"); const [subjectUserId, setSubjectUserId] = useState("");
  const [session, setSession] = useState<Session | null>(null); const [candidates, setCandidates] = useState<Candidate[]>([]); const [candidate, setCandidate] = useState<Candidate | null>(null); const [next, setNext] = useState<NextState | null>(null);
  const [clarifications, setClarifications] = useState<Clarification[]>([]); const [answers, setAnswers] = useState<Answer[]>([]); const [candidateLabel, setCandidateLabel] = useState(""); const [answerText, setAnswerText] = useState(""); const [certainty, setCertainty] = useState<keyof typeof certaintyLabels>("confirmed"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const scopeGeneration = useRef(0); const interviewGeneration = useRef(0);
  const fail = useCallback((reason: unknown) => { if (reason instanceof ApiError && [401, 403].includes(reason.status)) { ++scopeGeneration.current; ++interviewGeneration.current; setSession(null); setCandidates([]); setCandidate(null); setNext(null); setAnswers([]); setClarifications([]); } setError(reason instanceof Error ? reason.message : "تعذر إكمال الطلب."); }, []);
  function clearScope() { ++scopeGeneration.current; ++interviewGeneration.current; setSubjects([]); setSubjectUserId(""); setSession(null); setCandidates([]); setCandidate(null); setNext(null); setAnswers([]); setClarifications([]); setError(""); }

  useEffect(() => { let active = true; api<Context & { success: true }>("/api/tenant/context").then((data) => { if (!active) return; setContext(data); setProjectId(data.projects[0]?.id ?? ""); }).catch(fail); return () => { active = false; }; }, [fail]);
  useEffect(() => { if (!projectId || !unitId) return; const generation = scopeGeneration.current; api<{ users: Subject[]; allowOrganizationUnitSubject: boolean }>(`/api/tenant/guided-subjects?projectId=${encodeURIComponent(projectId)}&organizationUnitId=${encodeURIComponent(unitId)}`).then((data) => { if (generation !== scopeGeneration.current) return; setSubjects(data.users); setSubjectUserId(data.users[0]?.id ?? ""); if (!data.allowOrganizationUnitSubject) setSubjectType("user"); }).catch((reason) => { if (generation === scopeGeneration.current) fail(reason); }); }, [projectId, unitId, fail]);

  async function refreshCandidates(sessionId: string, selectId?: string) { const data = await api<{ candidates: Candidate[] }>(`/api/tenant/procedure-candidates?sessionId=${encodeURIComponent(sessionId)}`); setCandidates(data.candidates); const selected = data.candidates.find((item) => item.id === (selectId ?? candidate?.id)); if (selected) setCandidate(selected); }
  async function loadNext(activeSession: Session, activeCandidate?: Candidate | null) { const generation = ++interviewGeneration.current; const params = new URLSearchParams({ sessionId: activeSession.id }); if (activeCandidate) params.set("candidateId", activeCandidate.id); try { const data = await api<NextState>(`/api/tenant/guided-next-question?${params}`); if (generation !== interviewGeneration.current) return; setNext(data); setAnswerText(""); setCertainty("confirmed"); if (activeCandidate) { const [clarificationData, answerData] = await Promise.all([api<{ clarifications: Clarification[] }>(`/api/tenant/clarifications?sessionId=${activeSession.id}&candidateId=${activeCandidate.id}`), api<{ answers: Answer[] }>(`/api/tenant/guided-answers?sessionId=${activeSession.id}&candidateId=${activeCandidate.id}`)]); if (generation === interviewGeneration.current) { setClarifications(clarificationData.clarifications); setAnswers(answerData.answers); } } } catch (reason) { if (generation === interviewGeneration.current) fail(reason); } }
  async function openClarification(item: Clarification) { if (!session || !candidate) return; const generation = ++interviewGeneration.current; setError(""); try { const data = await api<NextState>(`/api/tenant/guided-next-question?sessionId=${session.id}&candidateId=${candidate.id}&clarificationId=${item.id}`); if (generation === interviewGeneration.current) { setNext(data); setAnswerText(""); setCertainty("confirmed"); } } catch (reason) { if (generation === interviewGeneration.current) fail(reason); } }
  async function startSession(event: FormEvent) { event.preventDefault(); if (!context || !projectId || !unitId || subjectType === "user" && !subjectUserId) return; setBusy(true); setError(""); try { const data = await api<{ sessionId: string }>("/api/tenant/documentation-sessions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId: context.user.companyId, projectId, organizationUnitId: unitId, subjectType, ...(subjectType === "user" ? { subjectUserId } : {}) }) }); const full = await api<{ session: Session }>(`/api/tenant/documentation-sessions?sessionId=${data.sessionId}`); setSession(full.session); await loadNext(full.session); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  function answerValue(question: Question, raw = answerText, selectedCertainty = certainty) { if (selectedCertainty === "unknown" || selectedCertainty === "needs_check") return { kind: "text", value: "غير معروف" }; if (question.answerKind === "boolean") return { kind: "boolean", value: raw === "true" }; if (question.answerKind === "number") return { kind: "number", value: Number(raw) }; if (question.answerKind === "duration") { const [value, unit = "minutes"] = raw.split("|"); return { kind: "duration", value: Number(value), unit }; } if (question.answerKind === "reference") return { kind: "reference", referenceType: question.id.includes("organization_unit") ? "organization_unit" : "user", referenceId: raw }; if (question.answerKind === "items") { const values = raw.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [first, second] = line.split("|").map((part) => part.trim()); if (question.id === "step.required_permissions") return { systemName: first, permission: second || "غير محدد" }; if (question.id === "step.exceptions") return { condition: first, action: second || "يحتاج توضيح" }; if (question.id === "step.documents") return { name: first, type: "other" }; return { name: first, ...(second ? { description: second } : {}) }; }); return { kind: "items", values }; } return { kind: question.answerKind, value: raw }; }
  async function submitAnswer(raw = answerText, selectedCertainty = certainty) { if (!session || !next?.nextQuestion || !next.subjectType || !next.subjectKey) return false; setBusy(true); setError(""); try { await api("/api/tenant/guided-answers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.id, ...(candidate && next.subjectType !== "session" ? { candidateId: candidate.id } : {}), subjectType: next.subjectType, subjectKey: next.subjectKey, ...(next.stepKey ? { stepKey: next.stepKey } : {}), questionId: next.nextQuestion.id, answer: answerValue(next.nextQuestion, raw, selectedCertainty), certainty: selectedCertainty, ...(selectedCertainty !== "confirmed" ? { uncertaintyNote: raw || certaintyLabels[selectedCertainty] } : {}) }) }); await loadNext(session, candidate); return true; } catch (reason) { fail(reason); return false; } finally { setBusy(false); } }
  async function transition(action: string) { if (!session) return; setBusy(true); setError(""); try { await api("/api/tenant/documentation-sessions", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.id, action }) }); const full = await api<{ session: Session }>(`/api/tenant/documentation-sessions?sessionId=${session.id}`); setSession(full.session); await refreshCandidates(session.id); await loadNext(full.session, candidate); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function addCandidate(event: FormEvent) { event.preventDefault(); if (!session || !candidateLabel.trim() || !next?.nextQuestion) return; setBusy(true); try { await api("/api/tenant/procedure-candidates", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.id, label: candidateLabel, sourceText: answerText || candidateLabel, originQuestionId: next.nextQuestion.id }) }); setCandidateLabel(""); await refreshCandidates(session.id); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function finalizeClassification(classification: "procedure" | "task" | "unclear") { if (!session || !candidate) return; setBusy(true); setError(""); try { const base = { sessionId: session.id, candidateId: candidate.id }; await api("/api/tenant/procedure-candidates", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...base, action: "classify", classification }) }); await api("/api/tenant/procedure-candidates", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(classification === "procedure" ? { ...base, action: "confirm_procedure" } : { ...base, action: "exclude", exclusionReason: classification === "task" ? "تم تأكيده كمهمة وليس إجراءً مستقلاً." : "المعلومات الحالية لا تكفي لاعتباره إجراءً مستقلاً." }) }); const data = await api<{ candidates: Candidate[] }>(`/api/tenant/procedure-candidates?sessionId=${session.id}`); setCandidates(data.candidates); const updated = data.candidates.find((item) => item.id === candidate.id) ?? null; setCandidate(updated); if (updated) await loadNext(session, updated); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function convert() { if (!session || !candidate) return; setBusy(true); try { const data = await api<{ procedureId: string }>("/api/tenant/procedure-conversion", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.id, candidateId: candidate.id, explicitConfirm: true }) }); setNotice(`تم إنشاء الإجراء بنجاح: ${data.procedureId}`); await refreshCandidates(session.id, candidate.id); } catch (reason) { fail(reason); } finally { setBusy(false); } }

  const question = next?.nextQuestion;
  return <div className="space-y-5">{error && <div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}{notice && <div className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</div>}
    {!session && <form onSubmit={startSession} className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-2"><label>المشروع<select className={inputClass} value={projectId} onChange={(e) => { clearScope(); setProjectId(e.target.value); setUnitId(""); }}>{context?.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>الوحدة التنظيمية<select className={inputClass} value={unitId} onChange={(e) => { clearScope(); setUnitId(e.target.value); }}><option value="">اختر الوحدة</option>{context?.organizationUnits.filter((unit) => context.user.role === "project_manager" || context.writableOrganizationUnitIds.includes(unit.id)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{context?.user.role !== "employee" && <label>موضوع الجلسة<select className={inputClass} value={subjectType} onChange={(e) => setSubjectType(e.target.value as typeof subjectType)}><option value="user">موظف</option><option value="organization_unit">الوحدة التنظيمية</option></select></label>}{subjectType === "user" && <label>الموظف<select className={inputClass} value={subjectUserId} onChange={(e) => setSubjectUserId(e.target.value)}>{subjects.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.email}</option>)}</select></label>}<button disabled={busy || !unitId || subjectType === "user" && !subjectUserId} className={`${primary} md:col-span-2`}>ابدأ جلسة التوثيق</button></form>}
    {session && <><section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">الجلسة الحالية</h2><p className="text-sm text-slate-500">المرحلة: {session.phase} · الحالة: {session.status}</p></div><div className="flex gap-2"><button className="rounded-lg border px-3 py-2" onClick={() => void transition(session.status === "paused" ? "resume" : "pause")}>{session.status === "paused" ? "استئناف" : "إيقاف مؤقت"}</button></div></div></section>
      <QualityPanel url={candidate && session.phase !== "discovery" ? `/api/tenant/quality-assessments?sessionId=${encodeURIComponent(session.id)}&candidateId=${encodeURIComponent(candidate.id)}` : `/api/tenant/quality-assessments?sessionId=${encodeURIComponent(session.id)}`} refreshKey={`${next?.nextQuestion?.id ?? "done"}:${clarifications.length}:${answers.length}:${candidates.map((item) => `${item.id}:${item.status}`).join("|")}`} />
      {session.phase === "discovery" && question && question.id !== "discovery.complete" && <form onSubmit={addCandidate} className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="text-lg font-bold">خلّينا نفتكر الشغل مع بعض</h2><p className="my-3 text-xl">{question.promptAr}</p><textarea className={inputClass} value={candidateLabel} onChange={(e) => setCandidateLabel(e.target.value)} placeholder="اكتب اسم شغل محتمل، ثم أضفه كمرشح"/><div className="mt-3 flex flex-wrap gap-2"><button className={primary} disabled={busy || !candidateLabel.trim()}>أضف مرشحًا</button><button type="button" className="rounded-xl border bg-white px-4 py-2" onClick={() => void submitAnswer("لا يوجد", "confirmed")}>التالي بدون مرشح</button></div></form>}
      <section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 font-bold">الأعمال التي اكتشفناها</h2><div className="flex flex-wrap gap-2">{candidates.map((item) => <button key={item.id} onClick={() => { setCandidate(item); void loadNext(session, item); }} className={`rounded-xl border px-3 py-2 ${candidate?.id === item.id ? "border-blue-700 bg-blue-50" : ""}`}>{item.label} · {item.status}</button>)}</div>{session.phase === "discovery" && question?.id === "discovery.complete" && <button className={`${primary} mt-4`} onClick={() => void submitAnswer("true", "confirmed").then((ok) => { if (ok) void transition("complete_discovery"); })}>نعم، اكتمل الاستكشاف</button>}</section>
      {candidate && question && session.phase !== "discovery" && <section className="rounded-2xl border bg-white p-5"><p className="text-sm text-blue-700">{candidate.label}{next?.stepNumber ? ` · الخطوة ${next.stepNumber}` : ""}</p><h2 className="my-3 text-xl font-bold">{question.promptAr}</h2><QuestionInput question={question} value={answerText} setValue={setAnswerText} subjects={subjects} units={context?.organizationUnits ?? []}/>{question.uncertainty && <div className="mt-3 flex flex-wrap gap-2">{Object.entries(certaintyLabels).map(([key, label]) => <button type="button" key={key} onClick={() => setCertainty(key as keyof typeof certaintyLabels)} className={`rounded-full border px-3 py-1 ${certainty === key ? "bg-slate-900 text-white" : ""}`}>{label}</button>)}</div>}<button className={`${primary} mt-4`} disabled={busy || certainty === "confirmed" && !answerText} onClick={() => void submitAnswer()}>حفظ والإجابة على التالي</button></section>}
      {candidate && next?.stage === "candidate_classification" && !question && <section className="rounded-2xl border bg-white p-5"><p>اقتراح المحرك: <b>{next.recommendation}</b> — القرار النهائي لك.</p><div className="mt-3 flex flex-wrap gap-2"><button className={primary} onClick={() => void finalizeClassification("procedure")}>تأكيد كإجراء</button><button className="rounded-xl border px-4 py-2" onClick={() => void finalizeClassification("task")}>مهمة</button><button className="rounded-xl border px-4 py-2" onClick={() => void finalizeClassification("unclear")}>غير واضح</button></div></section>}
      {session.phase === "classification" && candidates.some((item) => item.status === "confirmed_procedure") && candidates.every((item) => ["confirmed_procedure", "excluded"].includes(item.status)) && <button className={primary} onClick={() => void transition("begin_documentation")}>ابدأ توثيق الإجراءات المؤكدة</button>}
      {session.phase === "classification" && candidates.every((item) => item.status === "excluded") && <button className={primary} onClick={() => void transition("complete")}>إنهاء الجلسة بعد تصنيف كل الأعمال</button>}
      {candidate && clarifications.length > 0 && <section className="rounded-2xl border bg-amber-50 p-5"><h2 className="font-bold">نقاط تحتاج توضيح</h2>{clarifications.filter((item) => item.status === "open").map((item) => <div key={item.id} className="mt-2 flex items-center justify-between gap-3"><p>{item.severity === "required" ? "مطلوب" : "مستحسن"}: {item.summary}</p><button className="rounded-lg border bg-white px-3 py-1" onClick={() => void openClarification(item)}>توضيح الآن</button></div>)}</section>}
      {candidate && next && ["confirmation", "complete"].includes(next.stage) && <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">ده اللي فهمته منك</h2><p className="mt-2 font-semibold">{candidate.label}</p><div className="mt-4 space-y-4">{answers.filter((item) => item.questionId.startsWith("procedure.") && item.questionId !== "procedure.outputs").map((item) => <p key={item.id}><span className="font-medium">{summaryLabels[item.questionId] ?? item.questionId}:</span> {displayAnswer(item.answer)} <small className="text-slate-500">({certaintyLabels[item.certainty as keyof typeof certaintyLabels] ?? item.certainty})</small></p>)}{[...new Set(answers.filter((item) => item.stepKey).map((item) => item.stepKey as string))].sort().map((stepKey, index) => <div key={stepKey} className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">الخطوة {index + 1}</h3>{answers.filter((item) => item.stepKey === stepKey).map((item) => <p key={item.id} className="mt-1 text-sm"><span className="font-medium">{summaryLabels[item.questionId] ?? item.questionId}:</span> {displayAnswer(item.answer)} <small className="text-slate-500">({certaintyLabels[item.certainty as keyof typeof certaintyLabels] ?? item.certainty})</small></p>)}</div>)}{answers.filter((item) => item.questionId === "procedure.outputs").map((item) => <p key={item.id}><span className="font-medium">مخرجات الإجراء:</span> {displayAnswer(item.answer)}</p>)}</div><div className="mt-4 rounded-xl bg-amber-50 p-3"><p>نقاط مطلوبة: {next.blockers ?? 0} · تنبيهات مستحسنة: {next.warnings ?? 0}</p>{clarifications.filter((item) => item.status === "open").map((item) => <p key={item.id} className="mt-1 text-sm">{item.severity === "required" ? "مطلوب" : "مستحسن"}: {item.summary}</p>)}</div>{next.stage === "complete" && <button disabled={busy || (next.blockers ?? 0) > 0} className={`${primary} mt-4`} onClick={() => void convert()}>تحويل إلى إجراء رسمي</button>}</section>}
      {session.phase === "confirmation" && candidates.length > 0 && candidates.every((item) => ["converted", "excluded"].includes(item.status)) && <button className={primary} onClick={() => void transition("complete")}>إنهاء جلسة التوثيق</button>}
    </>}</div>;
}

function QuestionInput({ question, value, setValue, subjects, units }: { question: Question; value: string; setValue: (value: string) => void; subjects: Subject[]; units: Array<{ id: string; name: string }> }) {
  if (question.answerKind === "boolean") return <div className="flex gap-2"><button type="button" onClick={() => setValue("true")} className={`rounded-xl border px-4 py-2 ${value === "true" ? "bg-blue-700 text-white" : ""}`}>نعم</button><button type="button" onClick={() => setValue("false")} className={`rounded-xl border px-4 py-2 ${value === "false" ? "bg-blue-700 text-white" : ""}`}>لا</button></div>;
  if (question.answerKind === "choice") return <select className={inputClass} value={value} onChange={(e) => setValue(e.target.value)}><option value="">اختر</option>{question.choices?.map((choice) => <option key={choice} value={choice}>{choice}</option>)}</select>;
  if (question.answerKind === "reference") { const options = question.id.includes("organization_unit") ? units : subjects; return <select className={inputClass} value={value} onChange={(e) => setValue(e.target.value)}><option value="">اختر</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>; }
  if (question.answerKind === "duration") return <div className="flex gap-2"><input type="number" min="0" className={inputClass} value={value.split("|")[0] ?? ""} onChange={(e) => setValue(`${e.target.value}|${value.split("|")[1] || "minutes"}`)}/><select className={inputClass} value={value.split("|")[1] || "minutes"} onChange={(e) => setValue(`${value.split("|")[0] || "0"}|${e.target.value}`)}><option value="minutes">دقائق</option><option value="hours">ساعات</option><option value="days">أيام</option><option value="business_days">أيام عمل</option></select></div>;
  return question.answerKind === "items" ? <textarea className={inputClass} rows={4} value={value} onChange={(e) => setValue(e.target.value)} placeholder="عنصر في كل سطر. استخدم | للفصل بين جزأين عند الحاجة."/> : <input type={question.answerKind === "number" ? "number" : "text"} className={inputClass} value={value} onChange={(e) => setValue(e.target.value)}/>;
}
